default: all

CFLAGS := -Wall
XCC_INCLUDE :=

all: all-subdir
clean: clean-subdir

all-subdir clean-subdir: 
	@+(for dir in $(SUBDIR); \
	do \
		if [ -f $$dir/Makefile ]; \
		then \
			cd $$dir && $(MAKE) -s $(subst -subdir, , $@)|| exit 1; \
		fi \
	done)

%.o: %.c
	@cc -I$(XCC_INCLUDE) $(CFLAGS) -c $^ 
