#ifndef __OPTS_H__
#define __OPTS_H__


#include "stddefs.h"

#define UTIL_LOG_ENABLE TRUE
#define LINKED_LIST_LOG_ENABLE TRUE

#define HASH_TABLE_LOG_ENABLE TRUE
#define HASH_TABLE_INSERT_LOG_ENABLE FALSE
#define HASH_TABLE_SEARCH_LOG_ENABLE FALSE
#define HASH_TABLE_DELETE_LOG_ENABLE FALSE

#endif
